type = 'container'
run-cmd = ['docker-entrypoint.sh', 'postgres']
build = 'FROM postgres'
run-as-user = []
run-writable-file-system = true

[inputs]
POSTGRES_USER.type = 'text'
POSTGRES_PASSWORD.type = 'secret'
POSTGRES_DB.type = 'text'

[expose.5432]
type = 'tcp-internal'